name: Deploy Server to GCP

on:
  push:
    branches:
      - master
    paths:
      - './**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Build and Push Docker Image
      run: |-
        gcloud builds submit \
          --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/commute-server \
          ./

    - name: Deploy to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'commute-server'
        image: 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/commute-server'
        region: 'us-central1'
        env_vars: |-
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}
          PORT=5001
